# Generated by Django 4.2.7 on 2023-11-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='new', max_length=20),
        ),
    ]
