# Generated by Django 5.0.6 on 2024-05-22 20:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_groups', models.CharField(choices=[('admin', 'Admin'), ('librarian', 'Librarian'), ('patreon-on-site', 'Patreon (on-site)'), ('patreon-remote', 'Patreon (remote)')], max_length=20)),
                ('type', models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('document', 'Document'), ('audiobook', 'Audiobook'), ('audio', 'Audio'), ('video', 'Video'), ('podcast', 'Podcast')], default='book', max_length=20)),
                ('isbn', models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^.{13}$', 'ISBN must be exactly 13 characters')])),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('is_external', models.BooleanField(blank=True, default=False)),
                ('file_url', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.category')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
